/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parkflowmanagement;

/**
 *
 * @author Terence
 */
public class LoginUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginUI.class.getName());
    private int failedLoginAttempts = 0;
    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getRootPane().setDefaultButton(loginBtn);
    capsLockLabel.setVisible(false);
    // Force Dark Theme on all standard dialogs
javax.swing.UIManager.put("OptionPane.background", new java.awt.Color(80, 80, 80));
javax.swing.UIManager.put("Panel.background", new java.awt.Color(80, 80, 80));
javax.swing.UIManager.put("OptionPane.messageForeground", java.awt.Color.WHITE);
javax.swing.UIManager.put("Button.background", new java.awt.Color(100, 100, 100));
javax.swing.UIManager.put("Button.foreground", java.awt.Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        loginForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        forgotPassBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        capsLockLabel = new javax.swing.JLabel();
        showPasswordCheckBox = new javax.swing.JCheckBox();
        closeBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        loginPanel.setBackground(new java.awt.Color(102, 102, 102));
        loginPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginPanel.setLayout(new java.awt.BorderLayout());

        loginForm.setBackground(new java.awt.Color(50, 50, 50));
        loginForm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginForm.setMaximumSize(new java.awt.Dimension(320, 200));
        loginForm.setMinimumSize(new java.awt.Dimension(320, 200));
        loginForm.setPreferredSize(new java.awt.Dimension(320, 200));
        loginForm.setVerifyInputWhenFocusTarget(false);
        loginForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username:");
        loginForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 52, 68, -1));

        usernameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usernameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFieldFocusLost(evt);
            }
        });
        usernameField.addActionListener(this::usernameFieldActionPerformed);
        loginForm.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 49, 208, -1));

        passwordField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });
        passwordField.addActionListener(this::passwordFieldActionPerformed);
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordFieldKeyReleased(evt);
            }
        });
        loginForm.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 89, 209, -1));

        forgotPassBtn.setBackground(new java.awt.Color(169, 169, 169));
        forgotPassBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        forgotPassBtn.setForeground(new java.awt.Color(0, 0, 0));
        forgotPassBtn.setText("Forgot Password");
        forgotPassBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        forgotPassBtn.setMaximumSize(new java.awt.Dimension(120, 25));
        forgotPassBtn.setMinimumSize(new java.awt.Dimension(120, 25));
        forgotPassBtn.setPreferredSize(new java.awt.Dimension(130, 25));
        forgotPassBtn.addActionListener(this::forgotPassBtnActionPerformed);
        loginForm.add(forgotPassBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 174, -1, -1));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        loginForm.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 89, 67, -1));

        loginBtn.setBackground(new java.awt.Color(46, 139, 87));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("LOGIN");
        loginBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginBtn.addActionListener(this::loginBtnActionPerformed);
        loginForm.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 141, 273, -1));

        errorLabel.setBackground(new java.awt.Color(255, 102, 102));
        errorLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        errorLabel.setText("         ");
        loginForm.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 27, 280, -1));

        capsLockLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        capsLockLabel.setForeground(new java.awt.Color(255, 102, 51));
        capsLockLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        capsLockLabel.setText("Caps Lock is ON");
        capsLockLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        capsLockLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                capsLockLabelKeyReleased(evt);
            }
        });
        loginForm.add(capsLockLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 118, 118, -1));

        showPasswordCheckBox.setBackground(new java.awt.Color(51, 51, 51));
        showPasswordCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        showPasswordCheckBox.setText("Show Password");
        showPasswordCheckBox.setBorder(null);
        showPasswordCheckBox.setFocusable(false);
        showPasswordCheckBox.setHideActionText(true);
        showPasswordCheckBox.addItemListener(this::showPasswordCheckBoxItemStateChanged);
        showPasswordCheckBox.addActionListener(this::showPasswordCheckBoxActionPerformed);
        loginForm.add(showPasswordCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 117, -1, -1));

        closeBtn.setBackground(new java.awt.Color(178, 34, 34));
        closeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        closeBtn.setForeground(new java.awt.Color(255, 255, 255));
        closeBtn.setText("Close Window");
        closeBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closeBtn.setMaximumSize(new java.awt.Dimension(120, 25));
        closeBtn.setMinimumSize(new java.awt.Dimension(120, 25));
        closeBtn.setPreferredSize(new java.awt.Dimension(130, 25));
        closeBtn.addActionListener(this::closeBtnActionPerformed);
        loginForm.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 174, -1, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        loginForm.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 3, -1, -1));

        loginPanel.add(loginForm, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );

        loginPanel.add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );

        loginPanel.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        loginPanel.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setMinimumSize(new java.awt.Dimension(398, 80));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ParkFlow Management");
        jPanel4.add(jLabel4);

        loginPanel.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String inputUser = usernameField.getText().trim();
        String inputPass = new String(passwordField.getPassword());
        errorLabel.setText("");

        if (inputUser.isEmpty() || inputPass.isEmpty()) {
            errorLabel.setText("Username and password are required.");
            return;
        }

        // 1. Storage Variables (To hold data after the database closes)
        boolean isValid = false;
        String userRole = "";
        int accId = 0;

        // 2. Database Verification (Strictly isolated to release the lock)
        try (java.sql.Connection conn = parkflowmanagement.DatabaseUtil.getConnection();
             java.sql.PreparedStatement pstmt = conn.prepareStatement(
                 "SELECT account_id, role FROM users WHERE username = ? AND password = ? AND status = 'Active'")) {
             
            pstmt.setString(1, inputUser);
            pstmt.setString(2, inputPass);
            
            try (java.sql.ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    userRole = rs.getString("role");
                    accId = rs.getInt("account_id");
                    isValid = true;
                }
            }
        } catch (java.sql.SQLException ex) {
            ex.printStackTrace();
            errorLabel.setText("Database connection error.");
            return; // Halt if execution fails
        }

        // 3. Interface Launch (Executes ONLY after the connection is fully closed)
        if (isValid) {
            failedLoginAttempts = 0;
            if (userRole.equalsIgnoreCase("Admin")) {
                new AdminUI().setVisible(true);
                this.dispose();
            } else if (userRole.equalsIgnoreCase("Staff")) {
                new StaffUI(accId).setVisible(true);
                this.dispose();
            }
        } else {
            failedLoginAttempts++;
           if (failedLoginAttempts >= 3) {
                loginBtn.setEnabled(false);
                
                // 1. Threat Logging Execution
                try (java.sql.Connection logConn = parkflowmanagement.DatabaseUtil.getConnection();
                     java.sql.PreparedStatement logPstmt = logConn.prepareStatement(
                         "INSERT INTO system_logs (event_type, username, details, timestamp, is_read) VALUES (?, ?, ?, ?, 0)")) {
                    logPstmt.setString(1, "SECURITY_ALERT");
                    logPstmt.setString(2, inputUser.isEmpty() ? "UNKNOWN" : inputUser);
                    logPstmt.setString(3, "System lockout triggered. 3 failed login attempts.");
                    logPstmt.setString(4, new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date()));
                    logPstmt.executeUpdate();
                } catch (java.sql.SQLException ex) {}
                
                javax.swing.JOptionPane.showMessageDialog(this, "Terminal locked due to excessive failed attempts.\nSecurity alert transmitted to Administrator.", "Intrusion Prevention", javax.swing.JOptionPane.ERROR_MESSAGE);

                // 2. Automated Cooldown Protocol
                new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
                    int cooldown = 30; // 30-second lockout timer
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent e) {
                        cooldown--;
                        if (cooldown <= 0) {
                            loginBtn.setEnabled(true);
                            failedLoginAttempts = 0; // Reset intrusion counter
                            errorLabel.setText("");
                            ((javax.swing.Timer) e.getSource()).stop(); // Terminate background thread
                        } else {
                            errorLabel.setText("SYSTEM LOCKED. Try again in " + cooldown + "s");
                        }
                    }
                }).start();
                
            } else {
                errorLabel.setText("Invalid credentials. Attempts remaining: " + (3 - failedLoginAttempts));
           }
        }
      // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnActionPerformed

    private void forgotPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPassBtnActionPerformed
        // 1. Target Account Identification 
        javax.swing.JPanel userPanel = new javax.swing.JPanel();
        userPanel.setLayout(new java.awt.GridLayout(2, 1, 5, 5));
        userPanel.setBackground(new java.awt.Color(80, 80, 80));

        javax.swing.JLabel promptLabel = new javax.swing.JLabel("Enter your registered username:");
        promptLabel.setForeground(java.awt.Color.WHITE);
        promptLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

        javax.swing.JTextField usernameField = new javax.swing.JTextField();
        usernameField.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));

        userPanel.add(promptLabel);
        userPanel.add(usernameField);

        int result = javax.swing.JOptionPane.showConfirmDialog(this,
            userPanel, 
            "Account Recovery", 
            javax.swing.JOptionPane.OK_CANCEL_OPTION, 
            javax.swing.JOptionPane.PLAIN_MESSAGE);

        if (result != javax.swing.JOptionPane.OK_OPTION) {
            return; // Execution halted by user
        }

        String targetUsername = usernameField.getText().trim();
        if (targetUsername.isEmpty()) {
            return;
        }

        // 2. Multi-Data Extraction & Status Verification
        String[] questions = new String[3];
        String[] answers = new String[3];
        String accountStatus = "";
        boolean userFound = false;

        try (java.sql.Connection conn = parkflowmanagement.DatabaseUtil.getConnection();
             java.sql.PreparedStatement pstmt = conn.prepareStatement("SELECT status, sec_q1, sec_a1, sec_q2, sec_a2, sec_q3, sec_a3 FROM users WHERE username = ?")) {
             
            pstmt.setString(1, targetUsername);
            try (java.sql.ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    userFound = true;
                    accountStatus = rs.getString("status");
                    questions[0] = rs.getString("sec_q1");
                    answers[0] = rs.getString("sec_a1");
                    questions[1] = rs.getString("sec_q2");
                    answers[1] = rs.getString("sec_a2");
                    questions[2] = rs.getString("sec_q3");
                    answers[2] = rs.getString("sec_a3");
                } 
            }
        } catch (java.sql.SQLException e) {
            e.printStackTrace();
            return;
        } 
        // Read lock is automatically released here when the try-with-resources block closes.

        if (!userFound) {
            javax.swing.JOptionPane.showMessageDialog(this, "Username not found in system.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // STATUS ENFORCEMENT LOCK WITH THREAT LOGGING (Write operation now safe)
        if (!accountStatus.equalsIgnoreCase("Active")) {
            try (java.sql.Connection logConn = parkflowmanagement.DatabaseUtil.getConnection();
                 java.sql.PreparedStatement logPstmt = logConn.prepareStatement(
                     "INSERT INTO system_logs (event_type, username, details, timestamp, is_read) VALUES (?, ?, ?, ?, 0)")) {
                     
                logPstmt.setString(1, "SECURITY_ALERT");
                logPstmt.setString(2, targetUsername);
                logPstmt.setString(3, "Unauthorized password recovery attempt on " + accountStatus + " account.");
                logPstmt.setString(4, new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date()));
                logPstmt.executeUpdate();
                
            } catch (java.sql.SQLException ex) {
                ex.printStackTrace();
            }

            javax.swing.JOptionPane.showMessageDialog(this, 
                "Recovery Denied: Account is currently " + accountStatus + ". Security alert logged.", 
                "Security Lockout", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validation: Collect Valid Indices
      
        java.util.List<Integer> availableIndices = new java.util.ArrayList<>();
        for (int i = 0; i < 3; i++) {
            if (questions[i] != null && !questions[i].trim().isEmpty() && answers[i] != null && !answers[i].trim().isEmpty()) {
                availableIndices.add(i);
            }
        }

        if (availableIndices.size() < 2) {
            javax.swing.JOptionPane.showMessageDialog(this, "Insufficient security questions configured. Contact System Administrator.", "Recovery Halted", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // RANDOMIZATION PROTOCOL
        java.util.Collections.shuffle(availableIndices);

        // 3. Verification Execution
        int correctCount = 0;
        int incorrectCount = 0;
        int questionNumber = 1;

        for (int index : availableIndices) {
            String userAnswer = javax.swing.JOptionPane.showInputDialog(this, 
                "Security Question (" + questionNumber + "):\n" + questions[index], 
                "Identity Verification", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
                
            if (userAnswer == null) return; // Execution halted by user

            if (userAnswer.trim().equalsIgnoreCase(answers[index].trim())) {
                correctCount++;
            } else {
                incorrectCount++;
            }
            
            questionNumber++;

            // Evaluate Threshold Conditions
            if (correctCount == 2) {
                break; // Pass condition met immediately
            }
            
            if (incorrectCount == 2) {
                // 4. Failure Logging & Dual Notification
                try (java.sql.Connection conn = parkflowmanagement.DatabaseUtil.getConnection();
                     java.sql.PreparedStatement pstmt = conn.prepareStatement(
                         "INSERT INTO system_logs (event_type, username, details, timestamp) VALUES (?, ?, ?, ?)")) {
                         
                    pstmt.setString(1, "SECURITY_ALERT");
                    pstmt.setString(2, targetUsername);
                    pstmt.setString(3, "Failed security verification. 2 incorrect answers submitted.");
                    pstmt.setString(4, new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date()));
                    pstmt.executeUpdate();
                    
                } catch (java.sql.SQLException ex) {
                    ex.printStackTrace();
                }
                
                javax.swing.JOptionPane.showMessageDialog(this, "Authentication failed. 2 incorrect attempts recorded. Security alert transmitted to Administrator.", "Access Denied", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // 5. Password Reset Execution (Triggered strictly if correctCount == 2)
        if (correctCount == 2) {
            // Construct Custom Reset Interface
            javax.swing.JPanel resetPanel = new javax.swing.JPanel(new java.awt.GridLayout(0, 1, 2, 2));
            resetPanel.setBackground(new java.awt.Color(80, 80, 80));
            
            javax.swing.JLabel newPassLabel = new javax.swing.JLabel("New Password:");
            newPassLabel.setForeground(java.awt.Color.WHITE);
            javax.swing.JPasswordField newPassField = new javax.swing.JPasswordField();
            
            javax.swing.JLabel strengthLabel = new javax.swing.JLabel(" ");
            strengthLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 10));
            
            javax.swing.JLabel confPassLabel = new javax.swing.JLabel("Confirm Password:");
            confPassLabel.setForeground(java.awt.Color.WHITE);
            javax.swing.JPasswordField confPassField = new javax.swing.JPasswordField();
            
            javax.swing.JCheckBox showPassCheck = new javax.swing.JCheckBox("Show Passwords");
            showPassCheck.setBackground(new java.awt.Color(80, 80, 80));
            showPassCheck.setForeground(java.awt.Color.WHITE);
            
            // Visibility Toggle Logic
            showPassCheck.addActionListener(e -> {
                char echo = showPassCheck.isSelected() ? (char) 0 : '\u2022';
                newPassField.setEchoChar(echo);
                confPassField.setEchoChar(echo);
            });
            
            // Real-Time Strength Tracker Logic
            newPassField.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    String p = new String(newPassField.getPassword());
                    if (p.isEmpty()) { strengthLabel.setText(" "); return; }
                    
                    int score = 0;
                    if (p.length() >= 8) score++;
                    if (!p.equals(p.toLowerCase())) score++;
                    if (!p.equals(p.toUpperCase())) score++;
                    if (p.matches(".*\\d.*")) score++;
                    if (p.matches(".*[^a-zA-Z0-9].*")) score++;
                    
                    if (score <= 2) {
                        strengthLabel.setText("Strength: WEAK");
                        strengthLabel.setForeground(java.awt.Color.RED);
                    } else if (score >= 3 && score <= 4) {
                        strengthLabel.setText("Strength: MODERATE");
                        strengthLabel.setForeground(java.awt.Color.ORANGE);
                    } else if (score == 5) {
                        strengthLabel.setText("Strength: STRONG");
                        strengthLabel.setForeground(java.awt.Color.GREEN);
                    }
                }
            });
            
            resetPanel.add(newPassLabel);
            resetPanel.add(newPassField);
            resetPanel.add(strengthLabel);
            resetPanel.add(confPassLabel);
            resetPanel.add(confPassField);
            resetPanel.add(showPassCheck);
            
            boolean resetSuccessful = false;
            
            // Validation Loop
            while (!resetSuccessful) {
                int confirm = javax.swing.JOptionPane.showConfirmDialog(this, resetPanel, "Identity Verified: Reset Password", javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);
                
                if (confirm != javax.swing.JOptionPane.OK_OPTION) {
                    break; // Execution halted by user cancellation
                }
                
                String pass1 = new String(newPassField.getPassword());
                String pass2 = new String(confPassField.getPassword());
                
                if (pass1.isEmpty() || pass2.isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Fields cannot be empty.", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    continue; 
                }
                
                if (!pass1.equals(pass2)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Passwords do not match.", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    continue;
                }

                if (!isPasswordStrong(pass1)) {
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "SECURITY POLICY VIOLATION:\nNew password must be at least 8 characters long and contain:\n- One uppercase letter\n- One lowercase letter\n- One number\n- One special character", 
                        "Weak Password", 
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                    continue;
                }

                // Database Execution
                try (java.sql.Connection conn = parkflowmanagement.DatabaseUtil.getConnection();
                     java.sql.PreparedStatement pstmt = conn.prepareStatement("UPDATE users SET password = ? WHERE username = ?")) {
                     
                    pstmt.setString(1, pass1);
                    pstmt.setString(2, targetUsername);
                    pstmt.executeUpdate();
                    
                    resetSuccessful = true; // Breaks the loop
                    javax.swing.JOptionPane.showMessageDialog(this, "Account password updated successfully. You may now log in.", "System Notification", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    
                } catch (java.sql.SQLException e) {
                    e.printStackTrace();
                    javax.swing.JOptionPane.showMessageDialog(this, "Database error during password update.", "Execution Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    break;
                }
            }
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_forgotPassBtnActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
mouseX = evt.getX();
mouseY = evt.getY();        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
int screenX = evt.getXOnScreen();
int screenY = evt.getYOnScreen();
this.setLocation(screenX - mouseX, screenY - mouseY);        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
int response = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to exit the system?", "Confirm Exit", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE);

if (response == javax.swing.JOptionPane.YES_OPTION) {
    System.exit(0);
}        // TODO add your handling code here:
    }//GEN-LAST:event_closeBtnActionPerformed

    private void capsLockLabelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_capsLockLabelKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_capsLockLabelKeyReleased

    private void passwordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyReleased
boolean isCapsLockOn = java.awt.Toolkit.getDefaultToolkit().getLockingKeyState(java.awt.event.KeyEvent.VK_CAPS_LOCK);
capsLockLabel.setVisible(isCapsLockOn);        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldKeyReleased

    private void usernameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusGained
usernameField.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY, 2));        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldFocusGained

    private void usernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusLost
usernameField.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY, 1));        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldFocusLost

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY, 2));        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldFocusGained

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY, 1));        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldFocusLost

    private void showPasswordCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showPasswordCheckBoxItemStateChanged
        if (showPasswordCheckBox.isSelected()) {
            passwordField.setEchoChar((char) 0);
           
        } else {
            passwordField.setEchoChar('\u2022');
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_showPasswordCheckBoxItemStateChanged

    private void showPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showPasswordCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginUI().setVisible(true));
    }
    
    private boolean isPasswordStrong(String password) {
        if (password == null || password.length() < 8) return false;
        
        boolean hasUpper = !password.equals(password.toLowerCase());
        boolean hasLower = !password.equals(password.toUpperCase());
        boolean hasDigit = password.matches(".*\\d.*"); 
        boolean hasSpecial = password.matches(".*[^a-zA-Z0-9].*"); 
        
        return hasUpper && hasLower && hasDigit && hasSpecial;
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel capsLockLabel;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton forgotPassBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginForm;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JCheckBox showPasswordCheckBox;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
int mouseX;
int mouseY;
}
