/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parkflowmanagement;

/**
 *
 * @author Terence
 */
public class StaffUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffUI.class.getName());

    // 1. Global Variable Declaration
    private int currentStaffId;

    // 2. Primary Constructor (Modified to receive ID from LoginUI)
    public StaffUI(int staffId) {
        this.currentStaffId = staffId; 
        this.setUndecorated(true);
        initComponents();
        
        // --- INITIALIZATION & SHIFT GENERATION ---
        java.sql.Connection conn = null;
        try {
            conn = parkflowmanagement.DatabaseUtil.getConnection();
            
           // 2. Orphaned Shift Resumption & Auto-Purge Protocol
            int validOpenShiftId = -1;
            try (java.sql.PreparedStatement checkShift = conn.prepareStatement("SELECT shift_id FROM shift_reports WHERE account_id = ? AND (logout_time IS NULL OR logout_time = '') ORDER BY shift_id DESC")) {
                checkShift.setInt(1, currentStaffId);
                try (java.sql.ResultSet rsCheck = checkShift.executeQuery()) {
                    if (rsCheck.next()) {
                        validOpenShiftId = rsCheck.getInt("shift_id"); // Claims the most recent open shift
                    }
                    // AUTOPURGE: Force-closes any older duplicate ghost shifts (e.g., Shifts 30 & 31)
                    while (rsCheck.next()) {
                        int ghostShift = rsCheck.getInt("shift_id");
                        try (java.sql.PreparedStatement purgeStmt = conn.prepareStatement("UPDATE shift_reports SET logout_time = ?, shift_revenue = 0, declared_cash = 0, discrepancy = 0 WHERE shift_id = ?")) {
                            purgeStmt.setString(1, new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date()));
                            purgeStmt.setInt(2, ghostShift);
                            purgeStmt.executeUpdate();
                        }
                    }
                }
            }

            if (validOpenShiftId == -1) {
                String loginTime = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date());
                String sql = "INSERT INTO shift_reports (account_id, login_time, shift_revenue, declared_cash, discrepancy) VALUES (?, ?, 0, 0, 0)";
                try (java.sql.PreparedStatement pstmtShift = conn.prepareStatement(sql)) {
                    pstmtShift.setInt(1, currentStaffId); 
                    pstmtShift.setString(2, loginTime);
                    pstmtShift.executeUpdate();
                }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                "CRITICAL ERROR: Shift ledger could not be generated. Database may be locked.\nSystem revenue tracking will fail.", 
                "Database Locked", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        } finally {
            try { if (conn != null) conn.close(); } catch (Exception e){}
        }
        // ----------------------------------

        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        loadParkingSlots();
        updateStaffDashboard();
        
        processEntryBtn.setEnabled(false);
        processExitBtn.setEnabled(false);
        
        // --- AUTOMATED REAL-TIME SYNCHRONIZATION THREAD ---
        new javax.swing.Timer(5000, (java.awt.event.ActionEvent e) -> {
            // Prevent auto-refresh from interrupting active cashier inputs
            if (targetSlotLabel != null && (targetSlotLabel.getText().equals("NONE") || targetSlotLabel.getText().trim().isEmpty())) {
                loadParkingSlots();
                updateStaffDashboard();
            }
        }).start();
    }
    
    /**
     * Creates new form StaffUI
     */
    public StaffUI() {
        this.setUndecorated(true);
        initComponents();
        loadParkingSlots();

processEntryBtn.setEnabled(false);
processExitBtn.setEnabled(false);
        setLocationRelativeTo(null);
this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northStaffPanel = new javax.swing.JPanel();
        activeStaffLabel = new javax.swing.JLabel();
        shiftRevenueLabel = new javax.swing.JLabel();
        shiftVehiclesLabel = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        westStaffPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        targetSlotLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        plateNumberField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lostTicketCheck = new javax.swing.JCheckBox();
        overnightCheck = new javax.swing.JCheckBox();
        processEntryBtn = new javax.swing.JButton();
        processExitBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        categoryField = new javax.swing.JTextField();
        improperParkingCheck = new javax.swing.JCheckBox();
        centerScrollPanel = new javax.swing.JScrollPane();
        slotGridPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        northStaffPanel.setBackground(new java.awt.Color(153, 153, 153));
        northStaffPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        activeStaffLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        activeStaffLabel.setForeground(new java.awt.Color(255, 255, 255));
        activeStaffLabel.setText("Current User : ");

        shiftRevenueLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        shiftRevenueLabel.setForeground(new java.awt.Color(255, 255, 255));
        shiftRevenueLabel.setText("Shift Revenue : ₱ 0.00");

        shiftVehiclesLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        shiftVehiclesLabel.setForeground(new java.awt.Color(255, 255, 255));
        shiftVehiclesLabel.setText("Processed : 0");

        logoutBtn.setBackground(new java.awt.Color(178, 34, 34));
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("LOGOUT & END SHIFT");
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);

        javax.swing.GroupLayout northStaffPanelLayout = new javax.swing.GroupLayout(northStaffPanel);
        northStaffPanel.setLayout(northStaffPanelLayout);
        northStaffPanelLayout.setHorizontalGroup(
            northStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(northStaffPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(activeStaffLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shiftRevenueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shiftVehiclesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 438, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addContainerGap())
        );
        northStaffPanelLayout.setVerticalGroup(
            northStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(northStaffPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(northStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shiftVehiclesLabel)
                    .addComponent(logoutBtn)
                    .addComponent(shiftRevenueLabel)
                    .addComponent(activeStaffLabel))
                .addGap(4, 4, 4))
        );

        getContentPane().add(northStaffPanel, java.awt.BorderLayout.PAGE_START);

        westStaffPanel.setBackground(new java.awt.Color(51, 51, 51));
        westStaffPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        westStaffPanel.setForeground(new java.awt.Color(153, 153, 153));
        westStaffPanel.setOpaque(false);
        westStaffPanel.setPreferredSize(new java.awt.Dimension(200, 955));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selected Slot : ");

        targetSlotLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        targetSlotLabel.setForeground(new java.awt.Color(255, 255, 255));
        targetSlotLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        targetSlotLabel.setText(" ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Plate Number :");

        plateNumberField.setBackground(new java.awt.Color(255, 255, 255));
        plateNumberField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        plateNumberField.setForeground(new java.awt.Color(0, 0, 0));
        plateNumberField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vehicle Category :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Manual Surcharges :");

        lostTicketCheck.setBackground(new java.awt.Color(102, 102, 102));
        lostTicketCheck.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lostTicketCheck.setForeground(new java.awt.Color(255, 255, 255));
        lostTicketCheck.setText("Lost Ticket Penalty");
        lostTicketCheck.setEnabled(false);

        overnightCheck.setBackground(new java.awt.Color(102, 102, 102));
        overnightCheck.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        overnightCheck.setForeground(new java.awt.Color(255, 255, 255));
        overnightCheck.setText("Overnight Surcharge");
        overnightCheck.setEnabled(false);

        processEntryBtn.setBackground(new java.awt.Color(50, 255, 50));
        processEntryBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        processEntryBtn.setForeground(new java.awt.Color(0, 0, 0));
        processEntryBtn.setText("PROCESS ENTRY");
        processEntryBtn.addActionListener(this::processEntryBtnActionPerformed);

        processExitBtn.setBackground(new java.awt.Color(55, 55, 255));
        processExitBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        processExitBtn.setForeground(new java.awt.Color(0, 0, 0));
        processExitBtn.setText("PROCESS EXIT");
        processExitBtn.addActionListener(this::processExitBtnActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Insert Credentials : ");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        categoryField.setEditable(false);
        categoryField.setBackground(new java.awt.Color(255, 255, 255));
        categoryField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        categoryField.setForeground(new java.awt.Color(0, 0, 0));
        categoryField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        improperParkingCheck.setBackground(new java.awt.Color(102, 102, 102));
        improperParkingCheck.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        improperParkingCheck.setForeground(new java.awt.Color(255, 255, 255));
        improperParkingCheck.setText("Improper Parking Penalty");
        improperParkingCheck.setEnabled(false);
        improperParkingCheck.addActionListener(this::improperParkingCheckActionPerformed);

        javax.swing.GroupLayout westStaffPanelLayout = new javax.swing.GroupLayout(westStaffPanel);
        westStaffPanel.setLayout(westStaffPanelLayout);
        westStaffPanelLayout.setHorizontalGroup(
            westStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(westStaffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(westStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(westStaffPanelLayout.createSequentialGroup()
                        .addGroup(westStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plateNumberField)
                            .addComponent(categoryField)
                            .addComponent(targetSlotLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(processExitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(processEntryBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(westStaffPanelLayout.createSequentialGroup()
                                .addGroup(westStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(0, 18, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(westStaffPanelLayout.createSequentialGroup()
                        .addGroup(westStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(overnightCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(improperParkingCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lostTicketCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jSeparator5)
        );
        westStaffPanelLayout.setVerticalGroup(
            westStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(westStaffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(targetSlotLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plateNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lostTicketCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(improperParkingCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overnightCheck)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(processEntryBtn)
                .addGap(18, 18, 18)
                .addComponent(processExitBtn)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(westStaffPanel, java.awt.BorderLayout.LINE_START);

        slotGridPanel.setLayout(new java.awt.GridLayout(10, 5));
        centerScrollPanel.setViewportView(slotGridPanel);

        getContentPane().add(centerScrollPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void processEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processEntryBtnActionPerformed
    // 1. Input Validation
    String targetSlot = targetSlotLabel.getText();
    if (targetSlot.equals("NONE") || targetSlot.isEmpty()) {
       javax.swing.JOptionPane.showMessageDialog(this,"Select an available parking slot from the grid.", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    String plateNum = plateNumberField.getText().trim().toUpperCase();
    if (plateNum.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,"Plate number is strictly required.", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    String category = categoryField.getText().toString();
    String entryTime = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date());

    // 2. Dual-Table Database Transaction
    java.sql.Connection conn = null;
    java.sql.PreparedStatement pstmtSlot = null;
    java.sql.PreparedStatement pstmtHistory = null;

    try {
        conn = parkflowmanagement.DatabaseUtil.getConnection();
        conn.setAutoCommit(false); // Lock database for atomic transaction

      // Execution A: Claim Physical Slot 
        String updateSlotSql = "UPDATE parking_slots SET status = 'Occupied', current_plate = ?, current_category = ?, entry_time = ? WHERE slot_number = ?";
        pstmtSlot = conn.prepareStatement(updateSlotSql);
        pstmtSlot.setString(1, plateNum);
        pstmtSlot.setString(2, category);
        pstmtSlot.setString(3, entryTime); 
        pstmtSlot.setInt(4, Integer.parseInt(targetSlot));
        pstmtSlot.executeUpdate();

        // Identify Active Shift ID before saving to history
        int activeShiftId = -1;
        try (java.sql.Statement stmtShift = conn.createStatement();
             java.sql.ResultSet rsShift = stmtShift.executeQuery("SELECT shift_id FROM shift_reports WHERE account_id = " + currentStaffId + " AND (logout_time IS NULL OR logout_time = '') ORDER BY shift_id DESC LIMIT 1")) {
            if (rsShift.next()) {
                activeShiftId = rsShift.getInt("shift_id");
            }
        }
        
        // Execution B: Record Entry in Vehicle History
        String insertHistorySql = "INSERT INTO vehicle_history (shift_id, slot, plate_number, category, entry_time) VALUES (?, ?, ?, ?, ?)";
        pstmtHistory = conn.prepareStatement(insertHistorySql);
        pstmtHistory.setInt(1, activeShiftId);
        pstmtHistory.setString(2, targetSlot);
        pstmtHistory.setString(3, plateNum);
        pstmtHistory.setString(4, category);
        pstmtHistory.setString(5, entryTime);
        pstmtHistory.executeUpdate();

        conn.commit();

        // Execution C: Fetch Dynamic Rates for Ticket Printing
        double baseRate = 0, hourRate = 0, lostPenalty = 0, overnightSurcharge = 0;
        try (java.sql.Statement stmtRates = conn.createStatement();
             java.sql.ResultSet rsRates = stmtRates.executeQuery("SELECT setting_name, setting_value FROM system_settings")) {
            while (rsRates.next()) {
                String name = rsRates.getString("setting_name");
                double val = 0;
                try { val = Double.parseDouble(rsRates.getString("setting_value")); } catch (Exception e) {}
                
                if (category.contains("2-Wheel")) {
                    if (name.equals("base_fare_2wheel")) baseRate = val;
                    if (name.equals("hourly_rate_2wheel")) hourRate = val;
                } else {
                    if (name.equals("base_fare_4wheel")) baseRate = val;
                    if (name.equals("hourly_rate_4wheel")) hourRate = val;
                }
                if (name.equals("lost_ticket_penalty")) lostPenalty = val;
                if (name.equals("overnight_surcharge")) overnightSurcharge = val; // Extracts the surcharge rate
            }
        }

        // Virtual Ticket Generation
        javax.swing.JOptionPane.showMessageDialog(this, 
            "ENTRY PROCESSED\n----------------------\n" +
            "Plate: " + plateNum + "\n" +
            "Slot: " + targetSlot + "\n" +
            "Type: " + category + "\n" +
            "Time: " + entryTime + "\n----------------------\n" +
            "RATE SCHEDULE:\n" +
            "Base Fare (1st Hr) : ₱" + String.format("%.2f", baseRate) + "\n" +
            "Succeeding Hours : ₱" + String.format("%.2f", hourRate) + "/hr\n" +
            "Overnight Surcharge (11PM-4AM): ₱" + String.format("%.2f", overnightSurcharge) + "\n" +
            "Lost Ticket Penalty: ₱" + String.format("%.2f", lostPenalty) + "\n" +
            "----------------------\nWARNING: DO NOT LOSE THIS TICKET", 
            "Virtual Entry Ticket", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        
        // Interface Reset
        plateNumberField.setText("");
        if (categoryField != null) categoryField.setText("");
        processEntryBtn.setEnabled(false);
        targetSlotLabel.setText("NONE");
        
        loadParkingSlots();
        updateStaffDashboard();

    } catch (Exception e) {
        try { if (conn != null) conn.rollback(); } catch (java.sql.SQLException ex) {}
        e.printStackTrace();
       javax.swing.JOptionPane.showMessageDialog(this,"Error processing entry protocol.", "Execution Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } finally {
        try { 
            if (pstmtSlot != null) pstmtSlot.close();
            if (pstmtHistory != null) pstmtHistory.close();
            if (conn != null) { conn.setAutoCommit(true); conn.close(); } 
        } catch (Exception e){}
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_processEntryBtnActionPerformed

    private void processExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processExitBtnActionPerformed
        String targetSlot = targetSlotLabel.getText();
        if (targetSlot.equals("NONE") || targetSlot.isEmpty()) return;

        java.sql.Connection conn = null;
        try {
            conn = parkflowmanagement.DatabaseUtil.getConnection();
            conn.setAutoCommit(false); // Lock for atomic transaction

          // 1. Retrieve Entry Details
            String entryTimeStr = null;
            String category = "";
            double baseFare = 0, hourlyRate = 0, penalty = 0, overnight = 0, improperPenalty = 0;
            int gracePeriod = 0;

            try (java.sql.PreparedStatement pstmt = conn.prepareStatement("SELECT entry_time, current_category FROM parking_slots WHERE slot_number = ?")) {
                pstmt.setInt(1, Integer.parseInt(targetSlot));
                java.sql.ResultSet rs = pstmt.executeQuery();
                if (rs.next()) {
                    entryTimeStr = rs.getString("entry_time");
                    category = rs.getString("current_category");
                }
            }

            if (entryTimeStr == null || entryTimeStr.isEmpty()) {
                entryTimeStr = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date());
            }

            // Fetch System Rates
            try (java.sql.Statement stmt = conn.createStatement();
                 java.sql.ResultSet rs = stmt.executeQuery("SELECT setting_name, setting_value FROM system_settings")) {
                while (rs.next()) {
                    String name = rs.getString("setting_name");
                    double val = 0;
                    try { val = Double.parseDouble(rs.getString("setting_value")); } catch (Exception e){}
                    
                    if (category != null && category.contains("2-Wheel")) {
                        if (name.equals("base_fare_2wheel")) baseFare = val;
                        if (name.equals("hourly_rate_2wheel")) hourlyRate = val;
                    } else {
                        if (name.equals("base_fare_4wheel")) baseFare = val;
                        if (name.equals("hourly_rate_4wheel")) hourlyRate = val;
                    }
                    if (name.equals("grace_period")) gracePeriod = (int)val;
                    if (name.equals("lost_ticket_penalty")) penalty = val;
                    if (name.equals("overnight_surcharge")) overnight = val;
                    if (name.equals("improper_parking_penalty")) improperPenalty = val; // Extracted
                }
            }

            // 2. Fare Calculation Logic
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            java.util.Date entryDate = sdf.parse(entryTimeStr);
            java.util.Date exitDate = new java.util.Date();
            String exitTimeStr = sdf.format(exitDate);

            long diffInMs = exitDate.getTime() - entryDate.getTime();
            long diffInMins = diffInMs / (60 * 1000);
            
            double totalFare = 0;
            double extraHours = 0;
            double hourlyTotal = 0;
            
            double appliedLostPenalty = 0;
            double appliedOvernight = 0;
            double appliedImproper = 0;

            if (diffInMins > gracePeriod) {
                totalFare = baseFare;
                if (diffInMins > 60) {
                    extraHours = Math.ceil((double)(diffInMins - 60) / 60);
                    hourlyTotal = (extraHours * hourlyRate);
                    totalFare += hourlyTotal;
                }
            }

            if (lostTicketCheck.isSelected()) appliedLostPenalty = penalty;
            if (overnightCheck.isSelected()) appliedOvernight = overnight;
            if (improperParkingCheck.isSelected()) appliedImproper = improperPenalty; // Applied
            
            totalFare += (appliedLostPenalty + appliedOvernight + appliedImproper);

          

            // 3. Database Update Execution (Dynamic Revenue Reassignment)
            int activeShiftId = -1;
            try (java.sql.Statement stmt = conn.createStatement();
                 java.sql.ResultSet rsShift = stmt.executeQuery("SELECT shift_id FROM shift_reports WHERE account_id = " + currentStaffId + " AND (logout_time IS NULL OR logout_time = '') ORDER BY shift_id DESC LIMIT 1")) {
                if (rsShift.next()) activeShiftId = rsShift.getInt("shift_id");
            }

            // Update History Ledger (Actively overwrites shift_id to claim the fare)
            try (java.sql.PreparedStatement pstmt = conn.prepareStatement(
                "UPDATE vehicle_history SET exit_time = ?, fare = ?, shift_id = ? WHERE slot = ? AND exit_time IS NULL")) {
                pstmt.setString(1, exitTimeStr);
                pstmt.setDouble(2, totalFare);
                pstmt.setInt(3, activeShiftId);
                pstmt.setString(4, targetSlot);
                pstmt.executeUpdate();
            }
            
            // Reset Physical Slot
            try (java.sql.PreparedStatement pstmt = conn.prepareStatement(
                "UPDATE parking_slots SET status = 'Available', current_plate = NULL, current_category = NULL, entry_time = NULL WHERE slot_number = ?")) {
                pstmt.setInt(1, Integer.parseInt(targetSlot));
                pstmt.executeUpdate();
            }

            conn.commit();

            // 4. Billing Summary Breakdown & Interface Reset
            StringBuilder receiptBreakdown = new StringBuilder();
            receiptBreakdown.append("EXIT PROCESSED\n----------------------\n");
            receiptBreakdown.append("Duration: ").append(diffInMins).append(" mins\n");
            receiptBreakdown.append("Base Fare (1st Hr): ₱").append(String.format("%.2f", diffInMins > gracePeriod ? baseFare : 0.00)).append("\n");
            receiptBreakdown.append("Hourly (").append((int)extraHours).append(" hrs x ₱").append(hourlyRate).append("): ₱").append(String.format("%.2f", hourlyTotal)).append("\n");
            
            if (appliedOvernight > 0) {
                receiptBreakdown.append("Overnight Surcharge: ₱").append(String.format("%.2f", appliedOvernight)).append("\n");
            }
            if (appliedLostPenalty > 0) {
                receiptBreakdown.append("Lost Ticket Penalty: ₱").append(String.format("%.2f", appliedLostPenalty)).append("\n");
            }
            if (appliedImproper > 0) {
                receiptBreakdown.append("Improper Parking Penalty: ₱").append(String.format("%.2f", appliedImproper)).append("\n"); // Printed
            }
            
            receiptBreakdown.append("----------------------\n");
            receiptBreakdown.append("TOTAL CHARGE: ₱").append(String.format("%.2f", totalFare));

            javax.swing.JOptionPane.showMessageDialog(this,receiptBreakdown.toString(), "Billing Summary", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            plateNumberField.setText("");
            if (categoryField != null) categoryField.setText(""); 
            lostTicketCheck.setSelected(false);
            overnightCheck.setSelected(false);
            improperParkingCheck.setSelected(false); // Reset
            processExitBtn.setEnabled(false);
            targetSlotLabel.setText("NONE");
            loadParkingSlots();
            updateStaffDashboard();

        } catch (Exception e) {
            try { if (conn != null) conn.rollback(); } catch (java.sql.SQLException ex) {}
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,"Error processing exit calculation.", "Execution Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } finally {
            try { if (conn != null) { conn.setAutoCommit(true); conn.close(); } } catch (Exception e){}
        }
        
    // TODO add your handling code here:
    }//GEN-LAST:event_processExitBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        java.sql.Connection conn = null;
        try {
            conn = parkflowmanagement.DatabaseUtil.getConnection();

            // 1. Identify the TRUE Active Shift (Universal Search)
            int activeShiftId = -1;
            try (java.sql.Statement stmt = conn.createStatement();
                 java.sql.ResultSet rsShift = stmt.executeQuery("SELECT shift_id FROM shift_reports WHERE account_id = " + currentStaffId + " AND (logout_time IS NULL OR logout_time = '') ORDER BY shift_id DESC LIMIT 1")) {
                if (rsShift.next()) {
                    activeShiftId = rsShift.getInt("shift_id");
                }
            }

            if (activeShiftId == -1) {
                javax.swing.JOptionPane.showMessageDialog(this,"Fatal Error: No active shift found in database.", "Execution Halted", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 2. Fetch System Calculated Revenue
            double systemRevenue = 0;
            try (java.sql.PreparedStatement pstmt = conn.prepareStatement("SELECT SUM(fare) AS total FROM vehicle_history WHERE shift_id = ? AND exit_time IS NOT NULL")) {
                pstmt.setInt(1, activeShiftId);
                java.sql.ResultSet rs = pstmt.executeQuery();
                if (rs.next()) {
                    systemRevenue = rs.getDouble("total");
                }
            }

            // 3. Prompt for Physical Cash Declaration
           String input = javax.swing.JOptionPane.showInputDialog(this,
                "SHIFT END SUMMARY\nSystem Calculated: ₱" + String.format("%.2f", systemRevenue) + 
                "\n\nEnter Total Physical Cash Handover:", "");
        
            if (input == null || input.trim().isEmpty()) return; 

            // 4. Mathematical Discrepancy Calculation
            double declaredCash = 0;
            try {
                declaredCash = Double.parseDouble(input);
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this,"Invalid monetary amount entered.", "Execution Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            double discrepancy = declaredCash - systemRevenue;
            String logoutTime = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date());

            // 5. UPDATE the existing shift record
            try (java.sql.PreparedStatement pstmt = conn.prepareStatement("UPDATE shift_reports SET logout_time = ?, shift_revenue = ?, declared_cash = ?, discrepancy = ? WHERE shift_id = ?")) {
                pstmt.setString(1, logoutTime);
                pstmt.setDouble(2, systemRevenue);
                pstmt.setDouble(3, declaredCash);
                pstmt.setDouble(4, discrepancy);
                pstmt.setInt(5, activeShiftId);
                pstmt.executeUpdate();
            }

            javax.swing.JOptionPane.showMessageDialog(this,"Shift data saved. Logging out...", "Message", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            new LoginUI().setVisible(true);
            this.dispose();

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,"Database error during logout protocol.", "Execution Failure", javax.swing.JOptionPane.ERROR_MESSAGE);
        } finally {
            try { if (conn != null) conn.close(); } catch (Exception e){}
        }
    
      // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void improperParkingCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_improperParkingCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_improperParkingCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StaffUI().setVisible(true));
    }
    
private void loadParkingSlots() {
    // 1. Grid Topological Blueprint (7 Rows, 14 Columns)
    // Positive Integer = Slot Number | 0 = Road Aisle | -1 = Guardhouse | -2 = Exit | -3 = Entry
    int[][] mapMatrix = {
        {31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44},
        { 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0},
        { 1,  2,  3,  4,  5,  0, 45, 46,  0, 16, 17, 18, 19, 20},
        { 6,  7,  8,  9, 10,  0, 47, 48,  0, 21, 22, 23, 24, 25},
        { 0,  0,  0,  0,  0,  0, 49, 50,  0,  0,  0,  0,  0,  0},
        {11, 12, 13, 14, 15,  0,  0,  0,  0, 26, 27, 28, 29, 30},
        { 0,  0,  0,  0,  0, -2, -1, -1, -3,  0,  0,  0,  0,  0}
    };

    // 2. Structural Initialization
    slotGridPanel.removeAll();
    slotGridPanel.setLayout(new java.awt.GridLayout(7, 14, 5, 5));
    slotGridPanel.setBackground(new java.awt.Color(50, 50, 50));

    // 3. Database Data Extraction
    java.util.Map<Integer, Object[]> dbSlots = new java.util.HashMap<>();
    try (java.sql.Connection conn = parkflowmanagement.DatabaseUtil.getConnection();
         java.sql.Statement stmt = conn.createStatement();
         java.sql.ResultSet rs = stmt.executeQuery("SELECT slot_number, status, current_plate, current_category, slot_type, entry_time FROM parking_slots")) {

        while (rs.next()) {
            dbSlots.put(rs.getInt("slot_number"), new Object[]{
                rs.getString("status"),
                rs.getString("current_plate"),
                rs.getString("current_category"),
                rs.getString("slot_type"),
                rs.getString("entry_time")
            });
        }
    } catch (java.sql.SQLException ex) {
        ex.printStackTrace();
    }

    // 4. Interface Rendering via Blueprint Iteration
    for (int[] row : mapMatrix) {
        for (int cellValue : row) {
            
            if (cellValue > 0) {
                // Execution: Render Parking Slot
                Object[] data = dbSlots.get(cellValue);
                if (data == null) continue; // Skip if database is desynchronized with map

                String status = (String) data[0];
                String plate = (String) data[1];
                String category = (String) data[2];
                String slotType = (String) data[3];
                String entryTimeStr = (String) data[4];

                javax.swing.JButton slotBtn = new javax.swing.JButton(String.valueOf(cellValue));
                slotBtn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
                slotBtn.setFocusPainted(false);
                slotBtn.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLACK, 1));

                // State Visualization
                if (status.equalsIgnoreCase("Available")) {
                    slotBtn.setBackground(new java.awt.Color(46, 204, 113)); // Muted Green
                    slotBtn.setForeground(java.awt.Color.BLACK);
                } else {
                    slotBtn.setBackground(new java.awt.Color(231, 76, 60)); // Muted Red
                    slotBtn.setForeground(java.awt.Color.WHITE);
                }

               // Action Listener Binding
                slotBtn.addActionListener((java.awt.event.ActionEvent e) -> {
                    targetSlotLabel.setText(String.valueOf(cellValue));
                    
                    categoryField.setText(slotType);
                    categoryField.setEnabled(false); 

                    if (status.equalsIgnoreCase("Available")) {
                        // --- ENTRY MODE: Reset & Lock Everything ---
                        plateNumberField.setText("");
                        processEntryBtn.setEnabled(true);
                        processExitBtn.setEnabled(false);
                        
                        lostTicketCheck.setSelected(false);
                        lostTicketCheck.setEnabled(false); // Locked: Cannot lose a ticket before entry
                        
                        overnightCheck.setSelected(false); 
                        overnightCheck.setEnabled(false); // Locked: System controlled
                        
                        improperParkingCheck.setSelected(false);
                        improperParkingCheck.setEnabled(false); // Locked
                        
                    } else {
                        // --- EXIT MODE: Calculate & Secure ---
                        plateNumberField.setText(plate != null ? plate : "");
                        processEntryBtn.setEnabled(false);
                        processExitBtn.setEnabled(true);
                        
                        lostTicketCheck.setSelected(false);
                        lostTicketCheck.setEnabled(true); 
                        
                        improperParkingCheck.setSelected(false);
                        improperParkingCheck.setEnabled(true); // Unlocked for manual cashier application
                        
                        
                        // --- AUTOMATED OVERNIGHT SURCHARGE SCANNER ---
                        boolean isOvernight = false;
                        if (entryTimeStr != null && !entryTimeStr.isEmpty()) {
                            try {
                                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                                java.util.Date entryDate = sdf.parse(entryTimeStr);
                                java.util.Date exitDate = new java.util.Date(); // Current Time
                                
                                long diffMs = exitDate.getTime() - entryDate.getTime();
                                
                                // Rule A: Stayed >24 hours guarantees overnight crossover
                                if (diffMs >= 24 * 60 * 60 * 1000) {
                                    isOvernight = true;
                                } else {
                                    // Rule B: Hour-by-hour boundary scan
                                    java.util.Calendar cal = java.util.Calendar.getInstance();
                                    cal.setTime(entryDate);
                                    
                                    while (cal.getTime().before(exitDate)) {
                                        int hour = cal.get(java.util.Calendar.HOUR_OF_DAY);
                                        if (hour >= 23 || hour < 4) { // Hits 11 PM to 3:59 AM
                                            isOvernight = true; 
                                            break; 
                                        }
                                        cal.add(java.util.Calendar.HOUR_OF_DAY, 1);
                                    }
                                    
                                    // Rule C: Narrow exit overlap check
                                    if (!isOvernight) {
                                        cal.setTime(exitDate);
                                        int exitHour = cal.get(java.util.Calendar.HOUR_OF_DAY);
                                        if (exitHour >= 23 || exitHour < 4) isOvernight = true;
                                    }
                                }
                            } catch (Exception ex) {
                                ex.printStackTrace();
                            }
                        }
                        
                        // Force checkbox state and permanently lock it against tampering
                        overnightCheck.setSelected(isOvernight);
                        overnightCheck.setEnabled(false); // Locked: System controlled
                        // ----------------------------------------------
                    }
                });
                  
                slotGridPanel.add(slotBtn);

            } else if (cellValue == 0) {
                // Execution: Render Pathway (Dark Asphalt)
                javax.swing.JPanel pathway = new javax.swing.JPanel();
                pathway.setBackground(new java.awt.Color(70, 70, 70)); 
                slotGridPanel.add(pathway);

            } else {
                // Execution: Render Static Facilities / Navigation
                javax.swing.JLabel facilityLabel = new javax.swing.JLabel();
                facilityLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
                facilityLabel.setForeground(java.awt.Color.WHITE);
                facilityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                facilityLabel.setOpaque(true);
                facilityLabel.setBackground(new java.awt.Color(30, 30, 30));

                if (cellValue == -1) facilityLabel.setText("G");
                else if (cellValue == -2) facilityLabel.setText("EXIT");
                else if (cellValue == -3) facilityLabel.setText("ENTRY");

                slotGridPanel.add(facilityLabel);
            }
        }
    }

    // 5. Force Graphics Update
    slotGridPanel.revalidate();
    slotGridPanel.repaint();
}    

private void updateStaffDashboard() {
        try (java.sql.Connection conn = parkflowmanagement.DatabaseUtil.getConnection();
             java.sql.Statement stmt = conn.createStatement()) {
             
            int activeShiftId = -1;
            // Universal Search: Bypasses currentStaffId to locate the active terminal shift
            try (java.sql.ResultSet rsShift = stmt.executeQuery("SELECT shift_id FROM shift_reports WHERE account_id = " + currentStaffId + " AND (logout_time IS NULL OR logout_time = '') ORDER BY shift_id DESC LIMIT 1")) {
                if (rsShift.next()) {
                    activeShiftId = rsShift.getInt("shift_id");
                }
            }

            if (activeShiftId != -1) {
                // Calculates Processed Exits
                java.sql.ResultSet rsCount = stmt.executeQuery("SELECT COUNT(*) AS total FROM vehicle_history WHERE shift_id = " + activeShiftId + " AND exit_time IS NOT NULL");
                if (rsCount.next()) {
                    if (shiftVehiclesLabel != null) {
                        shiftVehiclesLabel.setText("Processed: " + rsCount.getInt("total"));
                    }
                }
                rsCount.close();

                // Calculates Validated Revenue
                java.sql.ResultSet rsRev = stmt.executeQuery("SELECT SUM(fare) AS revenue FROM vehicle_history WHERE shift_id = " + activeShiftId + " AND exit_time IS NOT NULL");
                if (rsRev.next()) {
                    double rev = rsRev.getDouble("revenue");
                    if (shiftRevenueLabel != null) {
                        shiftRevenueLabel.setText(String.format("Shift Revenue: \u20B1 %.2f", rev));
                    }
                }
                rsRev.close();
            }

        } catch (java.sql.SQLException e) {
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activeStaffLabel;
    private javax.swing.JTextField categoryField;
    private javax.swing.JScrollPane centerScrollPanel;
    private javax.swing.JCheckBox improperParkingCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JCheckBox lostTicketCheck;
    private javax.swing.JPanel northStaffPanel;
    private javax.swing.JCheckBox overnightCheck;
    private javax.swing.JTextField plateNumberField;
    private javax.swing.JButton processEntryBtn;
    private javax.swing.JButton processExitBtn;
    private javax.swing.JLabel shiftRevenueLabel;
    private javax.swing.JLabel shiftVehiclesLabel;
    private javax.swing.JPanel slotGridPanel;
    private javax.swing.JLabel targetSlotLabel;
    private javax.swing.JPanel westStaffPanel;
    // End of variables declaration//GEN-END:variables
}
